-- Default admin user will be created by AdminUserInitializer on startup
-- This migration is kept empty to maintain Flyway history
-- Username and password are configured via environment variables:
--   APP_ADMIN_USERNAME (default: admin)
--   APP_ADMIN_PASSWORD (default: admin123)
